/**
 * Merge themes/{name}/schema/*.yml fragments into a single data/{name}.yml
 * that Planetiler can consume.
 *
 * Fragments are merged in this order:
 *   1. _meta.yml        -> top-level (schema_name, attribution, ...)
 *   2. _sources.yml     -> sources: { ... }
 *   3. layers/*.yml     -> appended to layers: [ ... ]
 *
 * Each layers/*.yml is expected to be a YAML *sequence item* (starts with "- id: ...")
 * matching Planetiler's layer schema.
 */
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import YAML from "yaml";

const themeName = process.argv[2];
if (!themeName) {
  console.error("Usage: build-schema.ts <theme-name>");
  process.exit(1);
}

const themeDir = path.resolve("themes", themeName, "schema");
const layersDir = path.join(themeDir, "layers");
const outPath = path.resolve("data", `${themeName}.yml`);

const stripHeaderComments = (text: string): string =>
  text
    .split("\n")
    .filter((line) => !line.startsWith("#"))
    .join("\n");

const readYaml = async <T>(p: string): Promise<T> => {
  const text = await fs.readFile(p, "utf-8");
  return YAML.parse(stripHeaderComments(text)) as T;
};

const main = async () => {
  const meta = await readYaml<Record<string, unknown>>(
    path.join(themeDir, "_meta.yml"),
  );
  const sources = await readYaml<{ sources: Record<string, unknown> }>(
    path.join(themeDir, "_sources.yml"),
  );

  const layerFiles = (await fs.readdir(layersDir))
    .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
    .sort();

  const layers: unknown[] = [];
  const seenIds = new Set<string>();
  const errors: string[] = [];
  for (const f of layerFiles) {
    const parsed = await readYaml<unknown>(path.join(layersDir, f));
    const items = Array.isArray(parsed) ? parsed : [parsed];
    for (const item of items as Array<{ id?: string }>) {
      if (item?.id) {
        if (seenIds.has(item.id)) {
          errors.push(`${f}: duplicate schema layer id "${item.id}"`);
        }
        seenIds.add(item.id);
      }
      layers.push(item);
    }
  }
  if (errors.length > 0) {
    console.error("Contract violations:");
    for (const e of errors) console.error("  - " + e);
    process.exit(1);
  }

  const merged = { ...meta, ...sources, layers };
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(
    outPath,
    "# Generated by scripts/build-schema.ts. Do not edit by hand.\n" +
      "# Edit fragments under themes/" +
      themeName +
      "/schema/ and re-run `make " +
      themeName +
      "-build`.\n" +
      YAML.stringify(merged),
  );
  console.log(`wrote ${outPath} (${layers.length} layers)`);
};

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
