/**
 * Build a MapLibre style from a charites YAML root file.
 *
 * `charites build` (CLI) always emits JSON. We want a YAML intermediate too --
 * (1) so the AI agent can diff schema and style fragments in the same format,
 * (2) so the merged-but-pre-JSON shape is inspectable.
 *
 * Upstream charites does not expose a stable JS API: there is no `main`/`exports`
 * in @unvt/charites's package.json, so we reach into `dist/lib/yaml-parser.js`
 * directly. This is fragile; the existence of this wrapper is the evidence we
 * will cite when proposing `--format yaml` upstream
 * (https://github.com/unvt/charites).
 *
 * Usage:
 *   tsx scripts/build-style.ts <theme-name>
 *
 * Outputs:
 *   data/<theme-name>.style.yml   (merged, pre-JSON, for inspection / agent diff)
 *   data/<theme-name>.json        (MapLibre style.json, consumed by tileserver-gl)
 */
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import YAML from "yaml";
// @ts-expect-error -- @unvt/charites does not declare exports; reach into dist.
import { parser } from "@unvt/charites/dist/lib/yaml-parser.js";
// @ts-expect-error -- types not bundled in older releases
import { validateStyleMin } from "@maplibre/maplibre-gl-style-spec";

const themeName = process.argv[2];
if (!themeName) {
  console.error("Usage: build-style.ts <theme-name>");
  process.exit(1);
}

const rootYaml = path.resolve("themes", themeName, "style", "style.yml");
const outYaml = path.resolve("data", `${themeName}.style.yml`);
const outJson = path.resolve("data", `${themeName}.json`);

type MaplibreLayer = {
  id?: string;
  type?: string;
  "source-layer"?: string;
};

const stripHeader = (text: string): string =>
  text
    .split("\n")
    .filter((line) => !line.startsWith("#"))
    .join("\n");

const collectSchemaLayerIds = async (
  theme: string,
): Promise<Set<string>> => {
  const dir = path.resolve("themes", theme, "schema", "layers");
  const files = await fs.readdir(dir);
  const ids = new Set<string>();
  for (const f of files) {
    if (!f.endsWith(".yml") && !f.endsWith(".yaml")) continue;
    const text = await fs.readFile(path.join(dir, f), "utf-8");
    const parsed = YAML.parse(stripHeader(text)) as unknown;
    const layers = Array.isArray(parsed) ? parsed : [parsed];
    for (const layer of layers as Array<{ id?: string }>) {
      if (layer?.id) ids.add(layer.id);
    }
  }
  return ids;
};

const validate = (
  style: { layers?: MaplibreLayer[] },
  schemaLayerIds: Set<string>,
): string[] => {
  const errors: string[] = [];
  const seenStyleIds = new Set<string>();
  for (const layer of style.layers ?? []) {
    if (layer.id) {
      if (seenStyleIds.has(layer.id)) {
        errors.push(`duplicate style layer id "${layer.id}"`);
      }
      seenStyleIds.add(layer.id);
    }
    const sourceLayer = layer["source-layer"];
    if (sourceLayer && !schemaLayerIds.has(sourceLayer)) {
      errors.push(
        `style layer "${layer.id}" references source-layer "${sourceLayer}" that does not exist in the schema (known: ${[...schemaLayerIds].join(", ") || "(none)"})`,
      );
    }
  }
  return errors;
};

const main = async () => {
  const style = parser(rootYaml) as {
    layers?: MaplibreLayer[];
  } & Record<string, unknown>;

  const schemaLayerIds = await collectSchemaLayerIds(themeName);
  const errors = validate(style, schemaLayerIds);
  if (errors.length > 0) {
    console.error("Contract violations:");
    for (const e of errors) console.error("  - " + e);
    process.exit(1);
  }

  // MapLibre style spec validation -- catches expression typos (e.g. literal
  // arrays inside `match`), bad property types, unknown layer types, etc.
  // Returns an array of objects with at least { message }.
  const specErrors: Array<{ message: string; line?: number }> =
    validateStyleMin(style) ?? [];
  if (specErrors.length > 0) {
    console.error("MapLibre style spec errors:");
    for (const e of specErrors) {
      const loc = e.line ? ` (line ${e.line})` : "";
      console.error("  - " + e.message + loc);
    }
    process.exit(1);
  }

  await fs.mkdir(path.dirname(outJson), { recursive: true });
  await fs.writeFile(
    outYaml,
    "# Generated by scripts/build-style.ts. Do not edit by hand.\n" +
      "# Edit fragments under themes/" +
      themeName +
      "/style/ and re-run `make " +
      themeName +
      "-build`.\n" +
      YAML.stringify(style),
  );
  await fs.writeFile(outJson, JSON.stringify(style, null, 2));
  console.log(`wrote ${outYaml}`);
  console.log(`wrote ${outJson}`);
};

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
